{% set version = '1.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-betapart
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/betapart_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/betapart/betapart_{{ version }}.tar.gz
  sha256: baa52f8e53d417695f187174fb98b29a150d308c6e05888fa2c6c0b86ffae1aa

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ape
    - r-dosnow
    - r-fastmatch
    - r-foreach
    - r-geometry
    - r-itertools
    - r-minpack.lm
    - r-picante
    - r-rcdd
    - r-snow
  run:
    - r-base
    - r-ape
    - r-dosnow
    - r-fastmatch
    - r-foreach
    - r-geometry
    - r-itertools
    - r-minpack.lm
    - r-picante
    - r-rcdd
    - r-snow

test:
  commands:
    - $R -e "library('betapart')"           # [not win]
    - "\"%R%\" -e \"library('betapart')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=betapart
  license: GPL-2.0-or-later
  summary: Functions to compute pair-wise dissimilarities (distance matrices) and multiple-site
    dissimilarities, separating the turnover and nestedness-resultant components of
    taxonomic (incidence and abundance based), functional and phylogenetic beta diversity.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - Rassine

# Package: betapart
# Type: Package
# Title: Partitioning Beta Diversity into Turnover and Nestedness Components
# Version: 1.6
# Date: 2023-03-13
# Authors@R: c( person("Andres", "Baselga", email = "andres.baselga@usc.es", role = c("aut", "cre")), person("David", "Orme", role = "aut"), person("Sebastien", "Villeger", role = "aut"), person("Julien", "De Bortoli", role = "aut"), person("Fabien", "Leprieur", role = "aut"), person("Maxime", "Logez", role = "aut"), person("Sara", "Martinez-Santalla", role = "aut"), person("Ramiro", "Martin-Devasa", role = "aut"), person("Carola", "Gomez-Rodriguez", role = "aut"), person("Rosa M.", "Crujeiras", role = "aut"), person("Renato", "Henriques-Silva", role = "ctb") )
# Imports: ape, fastmatch, geometry, picante, rcdd, doSNOW, foreach, snow, itertools, minpack.lm
# Suggests: vegan
# Description: Functions to compute pair-wise dissimilarities (distance matrices) and multiple-site dissimilarities, separating the turnover and nestedness-resultant components of taxonomic (incidence and abundance based), functional and phylogenetic beta diversity.
# License: GPL (>= 2)
# NeedsCompilation: no
# Maintainer: Andres Baselga <andres.baselga@usc.es>
# Packaged: 2023-03-13 10:17:06 UTC; andre
# Author: Andres Baselga [aut, cre], David Orme [aut], Sebastien Villeger [aut], Julien De Bortoli [aut], Fabien Leprieur [aut], Maxime Logez [aut], Sara Martinez-Santalla [aut], Ramiro Martin-Devasa [aut], Carola Gomez-Rodriguez [aut], Rosa M. Crujeiras [aut], Renato Henriques-Silva [ctb]
# Repository: CRAN
# Date/Publication: 2023-03-13 17:10:15 UTC
